<?php

use App\Http\Controllers\Api\AuthController;
use App\Http\Controllers\Api\DashboardController;
use App\Http\Controllers\Api\UserController;
use App\Http\Controllers\Api\RoleController;
use App\Http\Controllers\Api\PermissionController;
use App\Http\Controllers\Api\SystemConfigController;
use App\Http\Controllers\Api\DataDictionaryController;
use App\Http\Controllers\Api\ProductController;
use App\Http\Controllers\Api\ProductCategoryController;
use App\Http\Controllers\Api\RegionController;
use App\Http\Controllers\Api\UnitController;
use App\Http\Controllers\Api\CurrencyController;
use App\Http\Controllers\Api\WarehouseController;
use App\Http\Controllers\Api\WarehouseLocationController;
use App\Http\Controllers\Api\InventoryController;
use App\Http\Controllers\Api\SupplierController;
use App\Http\Controllers\Api\CustomerController;
use App\Http\Controllers\Api\PurchaseOrderController;
use App\Http\Controllers\Api\SalesOrderController;
use App\Http\Controllers\Api\BomController;
use App\Http\Controllers\Api\ProcessRouteController;
use App\Http\Controllers\Api\ProductionPlanController;
use App\Http\Controllers\Api\WorkOrderController;
use App\Http\Controllers\Api\ProductionMaterialIssueController;
use App\Http\Controllers\Api\ProductionReportController;
use App\Http\Controllers\Api\ChartOfAccountController;
use App\Http\Controllers\Api\AccountingVoucherController;
use App\Http\Controllers\Api\GeneralLedgerController;
use App\Http\Controllers\Api\AccountsReceivableController;
use App\Http\Controllers\Api\AccountsPayableController;
use App\Http\Controllers\Api\CostAllocationController;
use App\Http\Controllers\Api\FinancialReportController;
use App\Http\Controllers\Api\WorkflowController;
use App\Http\Controllers\Api\WorkflowInstanceController;
use App\Http\Controllers\Api\ApprovalRecordController;
use App\Http\Controllers\Api\SalesReportController;
use App\Http\Controllers\Api\PurchaseReportController;
use App\Http\Controllers\Api\InventoryReportController;
use App\Http\Controllers\Api\CustomReportController;
use App\Http\Controllers\Api\NotificationController;
use App\Http\Controllers\Api\NotificationTemplateController;
use App\Http\Controllers\Api\OperationLogController;
use Illuminate\Support\Facades\Route;

Route::post('/login', [AuthController::class, 'login']);

Route::middleware('auth:sanctum')->group(function () {
    Route::post('/logout', [AuthController::class, 'logout']);
    Route::get('/me', [AuthController::class, 'me']);

    // Dashboard routes - 需要登录即可访问，聚合数据
    Route::get('/dashboard/stats', [DashboardController::class, 'getStats']);
    Route::get('/dashboard/pending-tasks', [DashboardController::class, 'getPendingTasks']);
    Route::get('/dashboard/recent-orders', [DashboardController::class, 'getRecentOrders']);

    Route::middleware('permission:users.manage')->apiResource('users', UserController::class);
    Route::middleware('permission:roles.manage')->apiResource('roles', RoleController::class);
    Route::middleware('permission:permissions.manage')->apiResource('permissions', PermissionController::class);
    Route::middleware('permission:system.config')->apiResource('system-configs', SystemConfigController::class);
    Route::middleware('permission:system.config')->get('system-configs/key/{key}', [SystemConfigController::class, 'getByKey']);
    Route::middleware('permission:system.config')->apiResource('data-dictionaries', DataDictionaryController::class);
    Route::middleware('permission:system.config')->get('data-dictionaries/type/{type}', [DataDictionaryController::class, 'getByType']);
    Route::middleware('permission:system.config')->get('data-dictionaries/types/list', [DataDictionaryController::class, 'getTypes']);

    Route::middleware('permission:product-categories.manage')->apiResource('product-categories', ProductCategoryController::class);
    Route::apiResource('regions', RegionController::class);
    Route::apiResource('units', UnitController::class);
    Route::apiResource('currencies', CurrencyController::class);
    Route::middleware('permission:products.manage')->apiResource('products', ProductController::class);
    Route::middleware('permission:warehouses.manage')->apiResource('warehouses', WarehouseController::class);
    Route::middleware('permission:warehouses.manage')->get('warehouse-locations', [WarehouseLocationController::class, 'index']);
    Route::middleware('permission:warehouses.manage')->post('warehouse-locations', [WarehouseLocationController::class, 'store']);
    Route::middleware('permission:warehouses.manage')->get('warehouse-locations/{id}', [WarehouseLocationController::class, 'show']);
    Route::middleware('permission:warehouses.manage')->put('warehouse-locations/{id}', [WarehouseLocationController::class, 'update']);
    Route::middleware('permission:warehouses.manage')->delete('warehouse-locations/{id}', [WarehouseLocationController::class, 'destroy']);
    Route::middleware('permission:inventory.view')->get('inventory', [InventoryController::class, 'index']);
    Route::middleware('permission:inventory.view')->get('inventory/{id}', [InventoryController::class, 'show']);
    Route::middleware('permission:inventory.stock-in')->post('inventory/stock-in', [InventoryController::class, 'stockIn']);
    Route::middleware('permission:inventory.stock-out')->post('inventory/stock-out', [InventoryController::class, 'stockOut']);
    Route::middleware('permission:inventory.transfer')->post('inventory/transfer', [InventoryController::class, 'transfer']);
    Route::middleware('permission:inventory.adjust')->post('inventory/adjust', [InventoryController::class, 'adjust']);
    Route::middleware('permission:inventory.view')->get('inventory-transactions', [InventoryController::class, 'transactions']);
    Route::middleware('permission:inventory.stocktake')->get('inventory-stocktakes', [InventoryController::class, 'stocktakes']);
    Route::middleware('permission:inventory.stocktake')->post('inventory-stocktakes', [InventoryController::class, 'createStocktake']);
    Route::middleware('permission:inventory.stocktake')->get('inventory-stocktakes/{id}', [InventoryController::class, 'showStocktake']);
    Route::middleware('permission:inventory.stocktake')->post('inventory-stocktakes/{id}/items', [InventoryController::class, 'addStocktakeItem']);
    Route::middleware('permission:inventory.stocktake')->post('inventory-stocktakes/{id}/complete', [InventoryController::class, 'completeStocktake']);

    Route::middleware('permission:suppliers.manage')->apiResource('suppliers', SupplierController::class);
    Route::middleware('permission:customers.manage')->apiResource('customers', CustomerController::class);
    Route::middleware('permission:purchase-orders.manage')->apiResource('purchase-orders', PurchaseOrderController::class);
    Route::middleware('permission:purchase-orders.manage')->post('purchase-orders/{id}/submit', [PurchaseOrderController::class, 'submit']);
    Route::middleware('permission:purchase-orders.approve')->post('purchase-orders/{id}/approve', [PurchaseOrderController::class, 'approve']);
    Route::middleware('permission:purchase-orders.receive')->post('purchase-orders/{id}/receive', [PurchaseOrderController::class, 'receive']);
    Route::middleware('permission:purchase-orders.manage')->post('purchase-orders/{id}/cancel', [PurchaseOrderController::class, 'cancel']);
    Route::middleware('permission:purchase-returns.manage')->get('purchase-returns', [PurchaseOrderController::class, 'returns']);
    Route::middleware('permission:purchase-returns.manage')->post('purchase-returns', [PurchaseOrderController::class, 'createReturn']);
    Route::middleware('permission:purchase-returns.manage')->get('purchase-returns/{id}', [PurchaseOrderController::class, 'showReturn']);
    Route::middleware('permission:purchase-returns.manage')->put('purchase-returns/{id}', [PurchaseOrderController::class, 'updateReturn']);
    Route::middleware('permission:purchase-returns.manage')->delete('purchase-returns/{id}', [PurchaseOrderController::class, 'destroyReturn']);
    Route::middleware('permission:purchase-returns.manage')->post('purchase-returns/{id}/submit', [PurchaseOrderController::class, 'submitReturn']);
    Route::middleware('permission:purchase-orders.approve')->post('purchase-returns/{id}/approve', [PurchaseOrderController::class, 'approveReturn']);
    Route::middleware('permission:purchase-settlements.manage')->get('purchase-settlements', [PurchaseOrderController::class, 'settlements']);
    Route::middleware('permission:purchase-settlements.manage')->post('purchase-settlements', [PurchaseOrderController::class, 'createSettlement']);
    Route::middleware('permission:purchase-settlements.manage')->get('purchase-settlements/{id}', [PurchaseOrderController::class, 'showSettlement']);
    Route::middleware('permission:purchase-orders.approve')->post('purchase-settlements/{id}/approve', [PurchaseOrderController::class, 'approveSettlement']);
    Route::middleware('permission:purchase-settlements.manage')->post('purchase-settlements/{id}/pay', [PurchaseOrderController::class, 'paySettlement']);
    Route::middleware('permission:sales-orders.manage')->apiResource('sales-orders', SalesOrderController::class);
    Route::middleware('permission:sales-orders.manage')->post('sales-orders/{id}/submit', [SalesOrderController::class, 'submit']);
    Route::middleware('permission:sales-orders.approve')->post('sales-orders/{id}/approve', [SalesOrderController::class, 'approve']);
    Route::middleware('permission:sales-orders.ship')->post('sales-orders/{id}/ship', [SalesOrderController::class, 'ship']);
    Route::middleware('permission:sales-orders.manage')->post('sales-orders/{id}/cancel', [SalesOrderController::class, 'cancel']);
    Route::middleware('permission:sales-returns.manage')->get('sales-returns', [SalesOrderController::class, 'returns']);
    Route::middleware('permission:sales-returns.manage')->post('sales-returns', [SalesOrderController::class, 'createReturn']);
    Route::middleware('permission:sales-returns.manage')->get('sales-returns/{id}', [SalesOrderController::class, 'showReturn']);
    Route::middleware('permission:sales-returns.manage')->post('sales-returns/{id}/submit', [SalesOrderController::class, 'submitReturn']);
    Route::middleware('permission:sales-orders.approve')->post('sales-returns/{id}/approve', [SalesOrderController::class, 'approveReturn']);
    Route::middleware('permission:sales-returns.manage')->post('sales-returns/{id}/cancel', [SalesOrderController::class, 'cancelReturn']);
    Route::middleware('permission:sales-settlements.manage')->get('sales-settlements', [SalesOrderController::class, 'settlements']);
    Route::middleware('permission:sales-settlements.manage')->post('sales-settlements', [SalesOrderController::class, 'createSettlement']);
    Route::middleware('permission:sales-settlements.manage')->get('sales-settlements/{id}', [SalesOrderController::class, 'showSettlement']);
    Route::middleware('permission:sales-orders.approve')->post('sales-settlements/{id}/approve', [SalesOrderController::class, 'approveSettlement']);
    Route::middleware('permission:sales-settlements.manage')->post('sales-settlements/{id}/receive', [SalesOrderController::class, 'receivePayment']);
    Route::middleware('permission:boms.manage')->apiResource('boms', BomController::class);
    Route::middleware('permission:boms.manage')->post('boms/{id}/set-default', [BomController::class, 'setDefault']);
    Route::middleware('permission:boms.manage')->post('boms/{id}/copy', [BomController::class, 'copy']);
    Route::middleware('permission:process-routes.manage')->apiResource('process-routes', ProcessRouteController::class);
    Route::middleware('permission:process-routes.manage')->post('process-routes/{id}/set-default', [ProcessRouteController::class, 'setDefault']);
    Route::middleware('permission:process-routes.manage')->post('process-routes/{id}/copy', [ProcessRouteController::class, 'copy']);
    Route::middleware('permission:production-plans.manage')->apiResource('production-plans', ProductionPlanController::class);
    Route::middleware('permission:production-plans.manage')->post('production-plans/{id}/submit', [ProductionPlanController::class, 'submit']);
    Route::middleware('permission:production-plans.manage')->post('production-plans/{id}/approve', [ProductionPlanController::class, 'approve']);
    Route::middleware('permission:work-orders.manage')->apiResource('work-orders', WorkOrderController::class);
    Route::middleware('permission:work-orders.manage')->post('work-orders/{id}/submit', [WorkOrderController::class, 'submit']);
    Route::middleware('permission:work-orders.manage')->post('work-orders/{id}/approve', [WorkOrderController::class, 'approve']);
    Route::middleware('permission:work-orders.manage')->post('work-orders/{id}/issue-material', [WorkOrderController::class, 'issueMaterial']);
    Route::middleware('permission:work-orders.manage')->post('work-orders/{id}/return-material', [WorkOrderController::class, 'returnMaterial']);
    Route::middleware('permission:work-orders.manage')->post('work-orders/{id}/complete', [WorkOrderController::class, 'complete']);
    Route::middleware('permission:work-orders.manage')->get('work-orders/{id}/material-issues', [WorkOrderController::class, 'materialIssues']);
    Route::middleware('permission:work-orders.manage')->get('work-orders/{id}/reports', [WorkOrderController::class, 'reports']);
    Route::middleware('permission:work-orders.manage')->get('production-material-issues', [ProductionMaterialIssueController::class, 'index']);
    Route::middleware('permission:work-orders.manage')->get('production-material-issues/{id}', [ProductionMaterialIssueController::class, 'show']);
    Route::middleware('permission:production-reports.manage')->apiResource('production-reports', ProductionReportController::class);
    Route::middleware('permission:chart-of-accounts.manage')->apiResource('chart-of-accounts', ChartOfAccountController::class);
    Route::middleware('permission:accounting-vouchers.manage')->apiResource('accounting-vouchers', AccountingVoucherController::class);
    Route::middleware('permission:accounting-vouchers.manage')->post('accounting-vouchers/{id}/submit', [AccountingVoucherController::class, 'submit']);
    Route::middleware('permission:accounting-vouchers.approve')->post('accounting-vouchers/{id}/start-approval', [AccountingVoucherController::class, 'startApproval']);
    Route::middleware('permission:accounting-vouchers.manage')->post('accounting-vouchers/{id}/cancel', [AccountingVoucherController::class, 'cancel']);
    Route::middleware('permission:accounting-vouchers.post')->post('accounting-vouchers/{id}/post', [AccountingVoucherController::class, 'post']);
    Route::middleware('permission:general-ledger.view')->get('general-ledger', [GeneralLedgerController::class, 'index']);
    Route::middleware('permission:general-ledger.view')->get('general-ledger/account/{id}/balance', [GeneralLedgerController::class, 'accountBalance']);
    Route::middleware('permission:accounts-receivable.manage')->apiResource('accounts-receivable', AccountsReceivableController::class);
    Route::middleware('permission:accounts-receivable.manage')->post('accounts-receivable/{id}/receive-payment', [AccountsReceivableController::class, 'receivePayment']);
    Route::middleware('permission:accounts-receivable.manage')->get('accounts-receivable/age-analysis', [AccountsReceivableController::class, 'ageAnalysis']);
    Route::middleware('permission:accounts-payable.manage')->apiResource('accounts-payable', AccountsPayableController::class);
    Route::middleware('permission:accounts-payable.manage')->post('accounts-payable/{id}/make-payment', [AccountsPayableController::class, 'makePayment']);
    Route::middleware('permission:accounts-receivable.manage')->apiResource('cost-allocations', CostAllocationController::class);
    Route::middleware('permission:approvals.handle')->post('cost-allocations/{id}/approve', [CostAllocationController::class, 'approve']);
    Route::middleware('permission:accounts-receivable.manage')->post('cost-allocations/{id}/complete', [CostAllocationController::class, 'complete']);
    Route::middleware('permission:financial-reports.view')->get('financial-reports/balance-sheet', [FinancialReportController::class, 'balanceSheet']);
    Route::middleware('permission:financial-reports.view')->get('financial-reports/income-statement', [FinancialReportController::class, 'incomeStatement']);
    Route::middleware('permission:workflows.manage')->apiResource('workflows', WorkflowController::class);
    Route::middleware('permission:workflows.manage')->apiResource('workflow-instances', WorkflowInstanceController::class);
    Route::middleware('permission:approvals.handle')->get('approval-records', [ApprovalRecordController::class, 'index']);
    Route::middleware('permission:approvals.handle')->get('approval-records/pending', [ApprovalRecordController::class, 'pendingApprovals']);
    Route::middleware('permission:approvals.handle')->post('approval-records/{instanceId}/approve', [ApprovalRecordController::class, 'approve']);
    Route::middleware('permission:approvals.handle')->post('approval-records/{instanceId}/reject', [ApprovalRecordController::class, 'reject']);
    Route::middleware('permission:approvals.handle')->get('approval-records/{instanceId}/history', [ApprovalRecordController::class, 'history']);
    Route::middleware('permission:sales-reports.view')->get('sales-reports/summary', [SalesReportController::class, 'summary']);
    Route::middleware('permission:sales-reports.view')->get('sales-reports/by-customer', [SalesReportController::class, 'byCustomer']);
    Route::middleware('permission:sales-reports.view')->get('sales-reports/by-product', [SalesReportController::class, 'byProduct']);
    Route::middleware('permission:sales-reports.view')->get('sales-reports/trend', [SalesReportController::class, 'trend']);
    Route::middleware('permission:purchase-reports.view')->get('purchase-reports/summary', [PurchaseReportController::class, 'summary']);
    Route::middleware('permission:purchase-reports.view')->get('purchase-reports/by-supplier', [PurchaseReportController::class, 'bySupplier']);
    Route::middleware('permission:purchase-reports.view')->get('purchase-reports/by-product', [PurchaseReportController::class, 'byProduct']);
    Route::middleware('permission:purchase-reports.view')->get('purchase-reports/trend', [PurchaseReportController::class, 'trend']);
    Route::middleware('permission:inventory-reports.view')->get('inventory-reports/turnover', [InventoryReportController::class, 'turnover']);
    Route::middleware('permission:inventory-reports.view')->get('inventory-reports/slow-moving', [InventoryReportController::class, 'slowMoving']);
    Route::middleware('permission:inventory-reports.view')->get('inventory-reports/valuation', [InventoryReportController::class, 'valuation']);
    Route::middleware('permission:inventory-reports.view')->get('inventory-reports/movement', [InventoryReportController::class, 'movement']);
    Route::middleware('permission:custom-reports.manage')->apiResource('custom-reports', CustomReportController::class);
    Route::middleware('permission:custom-reports.manage')->post('custom-reports/{id}/execute', [CustomReportController::class, 'execute']);
    // 通知功能 - 所有登录用户都可以查看自己的通知
    Route::get('notifications', [NotificationController::class, 'index']);
    Route::get('notifications/unread', [NotificationController::class, 'unread']);
    Route::get('notifications/unread-count', [NotificationController::class, 'unreadCount']);
    Route::get('notifications/{id}', [NotificationController::class, 'show']);
    Route::post('notifications/{id}/read', [NotificationController::class, 'markAsRead']);
    Route::post('notifications/read-all', [NotificationController::class, 'markAllAsRead']);
    Route::delete('notifications/{id}', [NotificationController::class, 'destroy']);
    Route::middleware('permission:system.config')->post('notifications/send', [NotificationController::class, 'send']);
    Route::middleware('permission:system.config')->post('notifications/send-by-template', [NotificationController::class, 'sendByTemplate']);
    Route::middleware('permission:system.config')->apiResource('notification-templates', NotificationTemplateController::class);
    Route::middleware('permission:system.config')->post('notification-templates/{id}/preview', [NotificationTemplateController::class, 'preview']);
    // 操作日志 - 需要系统配置权限
    Route::middleware('permission:system.config')->get('operation-logs', [OperationLogController::class, 'index']);
    Route::middleware('permission:system.config')->get('operation-logs/{id}', [OperationLogController::class, 'show']);
});
