<?php

use App\Http\Controllers\Api\AuthController;
use App\Http\Controllers\Api\UserController;
use App\Http\Controllers\Api\RoleController;
use App\Http\Controllers\Api\PermissionController;
use App\Http\Controllers\Api\SystemConfigController;
use App\Http\Controllers\Api\DataDictionaryController;
use App\Http\Controllers\Api\ProductController;
use App\Http\Controllers\Api\ProductCategoryController;
use App\Http\Controllers\Api\RegionController;
use App\Http\Controllers\Api\UnitController;
use App\Http\Controllers\Api\CurrencyController;
use App\Http\Controllers\Api\WarehouseController;
use App\Http\Controllers\Api\WarehouseLocationController;
use App\Http\Controllers\Api\InventoryController;
use App\Http\Controllers\Api\SupplierController;
use App\Http\Controllers\Api\CustomerController;
use App\Http\Controllers\Api\PurchaseOrderController;
use App\Http\Controllers\Api\SalesOrderController;
use App\Http\Controllers\Api\BomController;
use App\Http\Controllers\Api\ProcessRouteController;
use App\Http\Controllers\Api\ProductionPlanController;
use App\Http\Controllers\Api\WorkOrderController;
use App\Http\Controllers\Api\ProductionMaterialIssueController;
use App\Http\Controllers\Api\ProductionReportController;
use App\Http\Controllers\Api\ChartOfAccountController;
use App\Http\Controllers\Api\AccountingVoucherController;
use App\Http\Controllers\Api\GeneralLedgerController;
use App\Http\Controllers\Api\AccountsReceivableController;
use App\Http\Controllers\Api\AccountsPayableController;
use App\Http\Controllers\Api\CostAllocationController;
use App\Http\Controllers\Api\FinancialReportController;
use App\Http\Controllers\Api\WorkflowController;
use App\Http\Controllers\Api\WorkflowInstanceController;
use App\Http\Controllers\Api\ApprovalRecordController;
use App\Http\Controllers\Api\SalesReportController;
use App\Http\Controllers\Api\PurchaseReportController;
use App\Http\Controllers\Api\InventoryReportController;
use App\Http\Controllers\Api\CustomReportController;
use App\Http\Controllers\Api\NotificationController;
use App\Http\Controllers\Api\NotificationTemplateController;
use App\Http\Controllers\Api\OperationLogController;
use Illuminate\Support\Facades\Route;

Route::post('/login', [AuthController::class, 'login']);

Route::middleware('auth:sanctum')->group(function () {
    Route::post('/logout', [AuthController::class, 'logout']);
    Route::get('/me', [AuthController::class, 'me']);

    Route::middleware('permission:users.manage')->apiResource('users', UserController::class);
    Route::middleware('permission:roles.manage')->apiResource('roles', RoleController::class);
    Route::middleware('permission:permissions.manage')->apiResource('permissions', PermissionController::class);
    Route::middleware('permission:system.config')->apiResource('system-configs', SystemConfigController::class);
    Route::middleware('permission:system.config')->get('system-configs/key/{key}', [SystemConfigController::class, 'getByKey']);
    Route::middleware('permission:system.config')->apiResource('data-dictionaries', DataDictionaryController::class);
    Route::middleware('permission:system.config')->get('data-dictionaries/type/{type}', [DataDictionaryController::class, 'getByType']);
    Route::middleware('permission:system.config')->get('data-dictionaries/types/list', [DataDictionaryController::class, 'getTypes']);

    Route::middleware('permission:product-categories.manage')->apiResource('product-categories', ProductCategoryController::class);
    Route::get('regions', [RegionController::class, 'index']);
    Route::get('regions/{id}', [RegionController::class, 'show']);
    Route::get('units', [UnitController::class, 'index']);
    Route::get('units/{id}', [UnitController::class, 'show']);
    Route::get('currencies', [CurrencyController::class, 'index']);
    Route::get('currencies/{id}', [CurrencyController::class, 'show']);
    Route::middleware('permission:products.manage')->apiResource('products', ProductController::class);
    Route::middleware('permission:warehouses.manage')->apiResource('warehouses', WarehouseController::class);
    Route::get('warehouse-locations', [WarehouseLocationController::class, 'index']);
    Route::post('warehouse-locations', [WarehouseLocationController::class, 'store']);
    Route::get('warehouse-locations/{id}', [WarehouseLocationController::class, 'show']);
    Route::put('warehouse-locations/{id}', [WarehouseLocationController::class, 'update']);
    Route::delete('warehouse-locations/{id}', [WarehouseLocationController::class, 'destroy']);
    Route::middleware('permission:inventory.view')->get('inventory', [InventoryController::class, 'index']);
    Route::middleware('permission:inventory.view')->get('inventory/{id}', [InventoryController::class, 'show']);
    Route::middleware('permission:inventory.stock-in')->post('inventory/stock-in', [InventoryController::class, 'stockIn']);
    Route::middleware('permission:inventory.stock-out')->post('inventory/stock-out', [InventoryController::class, 'stockOut']);
    Route::middleware('permission:inventory.transfer')->post('inventory/transfer', [InventoryController::class, 'transfer']);
    Route::middleware('permission:inventory.adjust')->post('inventory/adjust', [InventoryController::class, 'adjust']);
    Route::middleware('permission:inventory.view')->get('inventory-transactions', [InventoryController::class, 'transactions']);
    Route::middleware('permission:inventory.stocktake')->get('inventory-stocktakes', [InventoryController::class, 'stocktakes']);
    Route::middleware('permission:inventory.stocktake')->post('inventory-stocktakes', [InventoryController::class, 'createStocktake']);
    Route::middleware('permission:inventory.stocktake')->get('inventory-stocktakes/{id}', [InventoryController::class, 'showStocktake']);
    Route::middleware('permission:inventory.stocktake')->post('inventory-stocktakes/{id}/items', [InventoryController::class, 'addStocktakeItem']);
    Route::middleware('permission:inventory.stocktake')->post('inventory-stocktakes/{id}/complete', [InventoryController::class, 'completeStocktake']);

    Route::middleware('permission:suppliers.manage')->apiResource('suppliers', SupplierController::class);
    Route::middleware('permission:customers.manage')->apiResource('customers', CustomerController::class);
    Route::apiResource('purchase-orders', PurchaseOrderController::class);
    Route::post('purchase-orders/{id}/approve', [PurchaseOrderController::class, 'approve']);
    Route::post('purchase-orders/{id}/receive', [PurchaseOrderController::class, 'receive']);
    Route::post('purchase-orders/{id}/cancel', [PurchaseOrderController::class, 'cancel']);
    Route::get('purchase-returns', [PurchaseOrderController::class, 'returns']);
    Route::post('purchase-returns', [PurchaseOrderController::class, 'createReturn']);
    Route::get('purchase-returns/{id}', [PurchaseOrderController::class, 'showReturn']);
    Route::post('purchase-returns/{id}/approve', [PurchaseOrderController::class, 'approveReturn']);
    Route::get('purchase-settlements', [PurchaseOrderController::class, 'settlements']);
    Route::post('purchase-settlements', [PurchaseOrderController::class, 'createSettlement']);
    Route::get('purchase-settlements/{id}', [PurchaseOrderController::class, 'showSettlement']);
    Route::post('purchase-settlements/{id}/approve', [PurchaseOrderController::class, 'approveSettlement']);
    Route::post('purchase-settlements/{id}/pay', [PurchaseOrderController::class, 'paySettlement']);
    Route::apiResource('sales-orders', SalesOrderController::class);
    Route::post('sales-orders/{id}/approve', [SalesOrderController::class, 'approve']);
    Route::post('sales-orders/{id}/ship', [SalesOrderController::class, 'ship']);
    Route::post('sales-orders/{id}/cancel', [SalesOrderController::class, 'cancel']);
    Route::get('sales-returns', [SalesOrderController::class, 'returns']);
    Route::post('sales-returns', [SalesOrderController::class, 'createReturn']);
    Route::get('sales-returns/{id}', [SalesOrderController::class, 'showReturn']);
    Route::post('sales-returns/{id}/approve', [SalesOrderController::class, 'approveReturn']);
    Route::get('sales-settlements', [SalesOrderController::class, 'settlements']);
    Route::post('sales-settlements', [SalesOrderController::class, 'createSettlement']);
    Route::get('sales-settlements/{id}', [SalesOrderController::class, 'showSettlement']);
    Route::post('sales-settlements/{id}/approve', [SalesOrderController::class, 'approveSettlement']);
    Route::post('sales-settlements/{id}/receive', [SalesOrderController::class, 'receivePayment']);
    Route::apiResource('boms', BomController::class);
    Route::post('boms/{id}/set-default', [BomController::class, 'setDefault']);
    Route::post('boms/{id}/copy', [BomController::class, 'copy']);
    Route::apiResource('process-routes', ProcessRouteController::class);
    Route::post('process-routes/{id}/set-default', [ProcessRouteController::class, 'setDefault']);
    Route::post('process-routes/{id}/copy', [ProcessRouteController::class, 'copy']);
    Route::apiResource('production-plans', ProductionPlanController::class);
    Route::post('production-plans/{id}/approve', [ProductionPlanController::class, 'approve']);
    Route::apiResource('work-orders', WorkOrderController::class);
    Route::post('work-orders/{id}/approve', [WorkOrderController::class, 'approve']);
    Route::post('work-orders/{id}/issue-material', [WorkOrderController::class, 'issueMaterial']);
    Route::post('work-orders/{id}/return-material', [WorkOrderController::class, 'returnMaterial']);
    Route::post('work-orders/{id}/complete', [WorkOrderController::class, 'complete']);
    Route::get('work-orders/{id}/material-issues', [WorkOrderController::class, 'materialIssues']);
    Route::get('work-orders/{id}/reports', [WorkOrderController::class, 'reports']);
    Route::get('production-material-issues', [ProductionMaterialIssueController::class, 'index']);
    Route::get('production-material-issues/{id}', [ProductionMaterialIssueController::class, 'show']);
    Route::apiResource('production-reports', ProductionReportController::class);
    Route::apiResource('chart-of-accounts', ChartOfAccountController::class);
    Route::apiResource('accounting-vouchers', AccountingVoucherController::class);
    Route::post('accounting-vouchers/{id}/post', [AccountingVoucherController::class, 'post']);
    Route::get('general-ledger', [GeneralLedgerController::class, 'index']);
    Route::get('general-ledger/account/{id}/balance', [GeneralLedgerController::class, 'accountBalance']);
    Route::apiResource('accounts-receivable', AccountsReceivableController::class);
    Route::post('accounts-receivable/{id}/receive-payment', [AccountsReceivableController::class, 'receivePayment']);
    Route::get('accounts-receivable/age-analysis', [AccountsReceivableController::class, 'ageAnalysis']);
    Route::apiResource('accounts-payable', AccountsPayableController::class);
    Route::post('accounts-payable/{id}/make-payment', [AccountsPayableController::class, 'makePayment']);
    Route::apiResource('cost-allocations', CostAllocationController::class);
    Route::post('cost-allocations/{id}/approve', [CostAllocationController::class, 'approve']);
    Route::post('cost-allocations/{id}/complete', [CostAllocationController::class, 'complete']);
    Route::get('financial-reports/balance-sheet', [FinancialReportController::class, 'balanceSheet']);
    Route::get('financial-reports/income-statement', [FinancialReportController::class, 'incomeStatement']);
    Route::apiResource('workflows', WorkflowController::class);
    Route::apiResource('workflow-instances', WorkflowInstanceController::class);
    Route::get('approval-records', [ApprovalRecordController::class, 'index']);
    Route::get('approval-records/pending', [ApprovalRecordController::class, 'pendingApprovals']);
    Route::post('approval-records/{instanceId}/approve', [ApprovalRecordController::class, 'approve']);
    Route::post('approval-records/{instanceId}/reject', [ApprovalRecordController::class, 'reject']);
    Route::get('approval-records/{instanceId}/history', [ApprovalRecordController::class, 'history']);
    Route::get('sales-reports/summary', [SalesReportController::class, 'summary']);
    Route::get('sales-reports/by-customer', [SalesReportController::class, 'byCustomer']);
    Route::get('sales-reports/by-product', [SalesReportController::class, 'byProduct']);
    Route::get('sales-reports/trend', [SalesReportController::class, 'trend']);
    Route::get('purchase-reports/summary', [PurchaseReportController::class, 'summary']);
    Route::get('purchase-reports/by-supplier', [PurchaseReportController::class, 'bySupplier']);
    Route::get('purchase-reports/by-product', [PurchaseReportController::class, 'byProduct']);
    Route::get('purchase-reports/trend', [PurchaseReportController::class, 'trend']);
    Route::get('inventory-reports/turnover', [InventoryReportController::class, 'turnover']);
    Route::get('inventory-reports/slow-moving', [InventoryReportController::class, 'slowMoving']);
    Route::get('inventory-reports/valuation', [InventoryReportController::class, 'valuation']);
    Route::get('inventory-reports/movement', [InventoryReportController::class, 'movement']);
    Route::apiResource('custom-reports', CustomReportController::class);
    Route::post('custom-reports/{id}/execute', [CustomReportController::class, 'execute']);
    Route::get('notifications', [NotificationController::class, 'index']);
    Route::get('notifications/unread', [NotificationController::class, 'unread']);
    Route::get('notifications/unread-count', [NotificationController::class, 'unreadCount']);
    Route::get('notifications/{id}', [NotificationController::class, 'show']);
    Route::post('notifications/{id}/read', [NotificationController::class, 'markAsRead']);
    Route::post('notifications/read-all', [NotificationController::class, 'markAllAsRead']);
    Route::delete('notifications/{id}', [NotificationController::class, 'destroy']);
    Route::post('notifications/send', [NotificationController::class, 'send']);
    Route::post('notifications/send-by-template', [NotificationController::class, 'sendByTemplate']);
    Route::apiResource('notification-templates', NotificationTemplateController::class);
    Route::post('notification-templates/{id}/preview', [NotificationTemplateController::class, 'preview']);
    Route::get('operation-logs', [OperationLogController::class, 'index']);
    Route::get('operation-logs/{id}', [OperationLogController::class, 'show']);
});
